swagger: '2.0'
info:
  title: IUNO TDM Payment Service API
  description: Create invoices, check payment and forward coins.
  version: "1.0.0"
# the domain of the service
host: localhost
# array of all schemes that your API supports
schemes:
  - https
  - http
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /invoices:
    post:
      summary: Add new invoices.
      parameters:
        - name: invoices
          description: list of invoices
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Invoice'
      responses:
        200:
          description: id of new invoice
          schema:
            $ref: '#/definitions/InvoiceId'
        400:
          description: bad request
          schema:
            $ref: '#/definitions/Error'
        503:
          description: service unavailable
          schema:
            $ref: '#/definitions/Error'
    get:
      summary: The invoices endpoint returns a list of all known invoices ids.
      responses:
        200:
          description: an array of invoices ids
          schema:
            type: array
            items:
              $ref: '#/definitions/InvoiceId'

  /invoices/{invoiceId}:
    get:
      summary: Returns information about the invoice to the provided id.
      operationId: getInvoiceById
      parameters:
        - name: invoiceId
          in: path
          type: string
          required: true
          description: the invoice id to get the information for
      responses:
        404:
          description: invoice not found
          schema:
            $ref: '#/definitions/Error'
        200:
          description: returns the information about the invoice
          schema:
            type: object
            properties:
              Invoice:
                $ref: "#/definitions/Invoice"
              CouponBalances:
                $ref: "#/definitions/AddressValuePair"
              Bip21Uri:
                description: bip21 invoice uri
                type: string
    delete:
      summary: Deletes the invoice to the provided ID.
      operationId: deleteInvoiceById
      parameters:
        - name: invoiceId
          in: path
          type: string
          required: true
          description: the id of the invoice to delete
      responses:
        404:
          description: invoice not found
          schema:
            $ref: '#/definitions/Error'
        200:
          description: invoice deleted

  /invoices/{invoiceId}/coupons:
    post:
      summary: Adds a coupon to the invoice.
      operationId: addCoupon
      parameters:
      - name: invoiceId
        in: path
        type: string
        required: true
        description: the id of the invoice the coupon is for
      - name: coupons
        in: body
        required: true
        description: array with coupon data
        schema:
          type: array
          items:
            $ref: "#/definitions/Coupon"
      responses:
        500:
          description: balance of coupon could not be retrieved
          schema:
            $ref: '#/definitions/Error'
        409:
          description: invoice already closed
          schema:
            $ref: '#/definitions/Error'
        404:
          description: invoice id not found
          schema:
            $ref: '#/definitions/Error'
        200:
          description: returns the balance of the coupon
          schema:
            $ref: '#/definitions/AddressValuePair'
    get:
      summary: Returns a list of coupons along with its values.
      operationId: getCoupons
      parameters:
      - name: invoiceId
        in: path
        type: string
        required: true
        description: the id of the invoice to get the coupons balances for
      responses:
        404:
          description: invoice id not found
          schema:
            $ref: '#/definitions/Error'
        200:
          description: returns the balance of the coupon
          schema:
            $ref: '#/definitions/AddressValuePair'

definitions:
  InvoiceId:
    type: string
    description: unique invoice id

  Coupon:
    type: string
    description: Bip38 encoded Bitcoin private key

  Address:
    type: string
    description: Bitcoin Base58 encoded public key hash address

  AddressValuePair:
    type: object
    properties:
      Address:
        $ref: "#/definitions/Address"
      Coin:
        type: integer
        format: int64
        description: value in Satoshis

  Invoice:
    type: object
    properties:
      TotalAmount:
        type: integer
        format: int64
        description: total amount of Satoshis that are requested to be paid
      Expiration:
        type: string
        format: date-time
        description: date after which this invoice is no longer valid
      Transfers:
        type: array
        description: array of all outputs with their values
        items:
          $ref: '#/definitions/AddressValuePair'

  Error:
    type: object
    properties:
      Message:
        type: string
        description: meaningful error message
